[tool.poetry]
name = "automation framework"
version = "0.1.0"
description = ""
authors = ["Praneetha"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
package-name = "^0.1"
requests = "^2.32.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
